### ISSUE TITLE
Feature request: please make `instanseg` a proper python package

### ISSUE THREAD

**Issue by psobolewskiPhD** [instanseg/instanseg#15]
Perhaps this is already on the road map, but making `instanseg` a proper python package with proper dependencies so it can be easily installed with pip and conda would be a big boon to broader usability.
Also, it would make it usable as a dependency for other packages, e.g. a napari plugin or whatever.

Perhaps the metrics and model shootout part could be optional? like `instanseg[metrics]` or something?

**Comment by ThibautGoldsborough** [comment]
InstanSeg now released to pypi under instanseg-torch
