### ISSUE TITLE
What is the released model pretrained on?

### ISSUE THREAD

**Issue by bowen118** [instanseg/instanseg#21]
What is the released model ([brightfield_nuclei.zip](https://github.com/instanseg/instanseg/releases/tag/instanseg_models_v1)) trained on? 

The paper mentions that for each evaluation dataset, the model was trained from scratch, so I am curious which of the datasets was the released model trained on, or was it an aggregate of the training data of multiple datasets?

**Comment by petebankhead** [comment]
You should find the datasets listed in the readme for the download.

**Comment by bowen118** [comment]
Thanks!
