### ISSUE TITLE
Question about using InstanSeg

### ISSUE THREAD

**Issue by NianzhenGu** [instanseg/instanseg#29]
Hi! Thanks for sharing this amating algorithm. I am using this software to run cell segmentation on multi-channel images, but I have encountered some problems:

1. I am using the pretrained model `"fluorescence_nuclei_and_cells"`. While running the `segmentation_minimal.ipynb` notebook, I found that some predicted cells are overlapping with each other. Additionally, I did not find post-processing step to solve this issue. The first image shows the nuclei mask. The second image shows the cell mask. The third image shows both. In the arrow part, it looks like the same mask is predicted as both cell and nuclei so we cannot visually distinguish. Also, one cell's mask is overlapping with another. 
![image](https://github.com/user-attachments/assets/2070aef9-1ed5-4f41-b106-69cd5f9bf8b8)
![image](https://github.com/user-attachments/assets/9e1278bc-fe31-4fad-86a6-9cfe65ec73c3)
![image](https://github.com/user-attachments/assets/33f5d9ad-f414-4137-bd34-04539e0c5f3e)

2. In the saved GeoJSON file, I noticed that some mask coordinates have two lists. Does this mean we have two predicted masks that belong to the same cell/nucleus? Do you think this is an issue with InstanSeg? 
![image](https://github.com/user-attachments/assets/7655c468-7659-4a27-a41d-789f6be22eaa)

3. I am struggling with many false positive predictions from InstanSeg, also some very small masks. So, for the `"fluorescence_nuclei_and_cells"` model, are there any parameters that can be adjusted or a threshold to select that can reduce the number of predictions?

Thank you very much for answering me!

**Comment by ThibautGoldsborough** [comment]
Hello, 

Apologies for the lack of documentation, we are aware of this and are working on it. 

The torchscript that is downloaded is an implementation of the class InstanSeg_Torchscript under utils/loss/instanseg_loss, you can give keyword arguments to InstanSeg.eval() or eval_small_image() etc... which will be passed on directly to the forward pass of InstanSeg_Torchscript.


For 1. By default InstanSeg resolves nuclei and cells as described in Fig. 2 of our [preprint](https://www.biorxiv.org/content/10.1101/2024.09.04.611150v1.full.pdf ) If you want to disable this behaviour you can pass the argument resolve_cell_and_nucleus=False 

For 2. You can remove small fragments by setting cleanup_fragments = True (There may be a performance cost). 

For 3. You can reduce false positives by setting mean_threshold = 0.2 for example. (default is 0.0).

If this answers your questions please remember to mark the issue as closed. 

Thanks!
