### ISSUE TITLE
Issues with image interpolation in .eval_medium_image()

### ISSUE THREAD

**Issue by Tomvl117** [instanseg/instanseg#32]
First of all, thank you for this fantastic tool, it has been a lot of fun playing around with this!

We were trying to use the sliding window inference function to analyze larger images, and it seems that the process runs into problem when it wants to interpolate the image to its original shape, since it is lacking a dimension (instanseg.py line 474):
```Python
if return_image_tensor:
  image = interpolate(image, size=original_shape[-2:], mode="bilinear")
```
There, images should have the shape ZCYX, but the image passed on is of dimensions CYX, which cannot be handled by `torch.nn.functional.interpolate()`.

By simply adding `image = image[None]` (which is also used in the `.eval_small_image()`) right before that line, the interpolation does not fail:
```Python
if return_image_tensor:
  image = image[None]
  image = interpolate(image, size=original_shape[-2:], mode="bilinear")
```

Then, the `image = image` on line 445 can be omitted as well :)

**Comment by ThibautGoldsborough** [comment]
Thank you for pointing this out. We're all at the I2K conference so may not be able to fix this immediately. I'm a little surprise you run in to this error though, do you get it when calling the function from the notebook with one of the example images? If not, can you share the shape of the image you are giving to the function? thanks

**Comment by Tomvl117** [comment]
We created a fresh conda environment with Python 3.9, ran `pip install instanseg-torch`, and explicitly called either `.eval_small_image()` or `.eval_medium_image()` with the same input image of size (14, 1590, 1590) (C, Y, X). This image has a pixelsize of ~0.454, so the images get rescaled, and need to be upscaled by `torch.nn.functional.interpolate()`. `.eval_small_image()` handles this very well by adding the 4th dimension required for `interpolate()`, but this dimension is not added correctly in `.eval_medium_image()` and thus the interpolation fails for the same image.

**Comment by markdane** [comment]
Thank you for this valuable package. I also ran into this error on my images and made the edit described by Tomvl117 above. The eval_medium_image code seems to be working well for my 6kx6k images. I do want to segment whole tissue images that are 45k x 45k pixels and will look to the experimental eval_whole_slide_image code.

**Comment by ThibautGoldsborough** [comment]
Thanks Tomvl117 and markdane, 

This is now fixed, along with a range of other small edge cases.

As with the eval_whole_slide_image, it's a bit inelegant and not particularly fast (and I only tested it for brightfield_nuclei on a HE image). It's fustrating I can't find a library for this sort of functionality. Writing it myself was not fun. 

In the meanwhile you can increase this threshold if you have enough RAM to fit your entire image.
 instanseg_brightfield.medium_image_threshold = 10000 * 10000 #max number of image pixels that could be loaded in RAM.
