### ISSUE TITLE
Question about the data used in training fluorescence_nuclei_and_cells model

### ISSUE THREAD

**Issue by NianzhenGu** [instanseg/instanseg#41]
Hi! I want to clarify the data used in training the fluorescence_nuclei_and_cells model. In the paper, you mentioned two datasets: **TissueNet** and **CPDMI 2023**. In the paper, you stated that 

> We use TissueNet v1.1 to benchmark the of segmentation performance of InstanSeg. 

However, in the table below, it seems that you also use it for training. Also, I find that the readme of  fluorescence_nuclei_and_cells model and it says that it only uses **CPDMI 2023**. May I clarify whether TissueNet is used not only for benchmarking but also for training? Thank you very much!

![{C411B1A0-3068-4498-907E-59943F547021}](https://github.com/user-attachments/assets/a74af983-4abb-4d1b-b289-4a84fb8e5530)

**Comment by ThibautGoldsborough** [comment]
Hey! 
The "fluorescence_cells_and_nuclei" model was only rained on CPDMI, as stated in the README. 
TissueNet was released with a strange license, which makes it ambiguous for us to share publicly. InstanSeg is Apache 2.0, but TissueNet is a lot more restrictive than Apache 2.0. 

We have contacted the owners of TissueNet to try and clarify but so far they have not replied.  

In the meanwhile, you are completely free to train your own InstanSeg on TissueNet and CPDMI (although from our experience, the accuracy is not always much better).
