### ISSUE TITLE
Request regarding a finetuning / training functionality

### ISSUE THREAD

**Issue by anwai98** [instanseg/instanseg#48]
Hi team,

First of all, thanks for the awesome work!

I see that the current training / finetuning framework is located at `instanseg/scripts/train.py`. I think it would be nice to create a training functionality which a user would call in their python scripts (or building other downstream workflows) (apologies if I overlooked something similar that already exists in the package)

Thanks in advance!

**Comment by ThibautGoldsborough** [comment]
Hi ! 

Just added a new notebook showing how to call the training function in a python script. 
It won't let you finetune any of the public model,  you'll have to train from scratch.

Best,
Thibaut

**Comment by anwai98** [comment]
Nice, thanks. I'll check it out!
