### ISSUE TITLE
Conversion to ONNX failing

### ISSUE THREAD

**Issue by steeve-gh** [instanseg/instanseg#54]
Hello, I am trying to convert the trained model that is provided in the repos (fluorescence_nuclei_and_cells/instanseg.pt) to ONNX but unfortunately I am getting errors.
The issue seems to be related to torchscripts only as tried to convert a dummy model and it seems to be working just fine.

Could you share the configuration of the model you created in the released v0.0.1 files in order to be able to recreate the same environment?

Thank you!

**Comment by ThibautGoldsborough** [comment]
Hi,
Can you explain what you mean by dummy model?

**Comment by steeve-gh** [comment]
Sure! I simply trained a model from my side, quickly (only 1 epoch) on one of the data set I downloaded as explained. This is a model that performs poorly since I didn't train it properly but I was just curious to see if I manage to convert the actual Model (nn.Module) since I couldn't make the conversion work using the torchscript file.

**Comment by ThibautGoldsborough** [comment]
You can download the raw model weights on[ google drive ](
https://drive.google.com/file/d/19rexYoVSsGFA6JwSaIddeIa9uvveE2ZW/view?usp=drive_link):


This is a temporary solution and the link will eventually go down, we'll figure out a more permanent way of sharing the raw models and versions in a future version.

**Comment by ThibautGoldsborough** [comment]
If I'm correct though, onnx uses tracing as opposed to scripting, so the model might throw an error when there are no detected objects for example. Onnx support would be nice, but is very unlikely to replace torchscript in the project.

**Comment by steeve-gh** [comment]
Thank you very much, I'll give it a try and see if I manage to get some results with that

**Comment by steeve-gh** [comment]
Hello again, I wanted to share some updates (which leads me to closing the issue I guess).
I managed to load the model properly, to convert it to onnx and to run actual predictions on actual images !
Here are the results:
pytorch model:
![pytorch_prediction](https://github.com/user-attachments/assets/444cca66-6b24-4469-9392-81465ad14ac9)

onnx model:
![onnx_prediction](https://github.com/user-attachments/assets/6474c7ef-1e15-4706-9f51-cb4ca7f68f8e)

thank you for sharing the configuration and congrats with your research, it is truly thrilling

**Comment by ThibautGoldsborough** [comment]
Hey, thanks for reporting these results, could you just clarify whether the ONNX you made is entirely self-contained? (Including the postprocessing). Or are you still relying on the instanseg postprocessing to handle the onnx outputs?

Thanks

**Comment by steeve-gh** [comment]
Hello !
No I just converted the model (to get the 1.10.h,w output).
Nevertheless, in addition to that I also converted all the postprocessing to remove links to pytorch. So I am now using onnx and a mix of numpy, scipy, etc.
So the solution I used to generate such results are not relying on torch anymore and includes "pre processing" to setup the images (similar to what is currently done in Instanseg project), onnx model, converted postprocessing

**Comment by fanweiya** [comment]
> Hello ! No I just converted the model (to get the 1.10.h,w output). Nevertheless, in addition to that I also converted all the postprocessing to remove links to pytorch. So I am now using onnx and a mix of numpy, scipy, etc. So the solution I used to generate such results are not relying on torch anymore and includes "pre processing" to setup the images (similar to what is currently done in Instanseg project), onnx model, converted postprocessing
 
It would be really great if you could share code. Looking forward to your reply.Thank you!

**Comment by ajinkya-kulkarni** [comment]
Hi @steeve-gh 
pinging you again, sorry. Could you share the source-code for converting the model to ONNX?

**Comment by ThibautGoldsborough** [comment]
I'm intrigued why you would want to use ONNX instead of torchscript. Rewriting the postprocessing steps in numpy will lose gpu support and will make the model less portable (it will be dependent on python). 
Is there a reason you don't have access to pytorch? Or do you just need to separate the model from the postprocessing?

**Comment by KevinCortacero** [comment]
Hi @ThibautGoldsborough ,
One reason for using ONNX is to eliminate the dependency on the Torch package (which is quite resource-intensive).
Generally speaking, it’s also useful to just use ChannelNet on its own (with or without ONNX, for that matter) or to rework the overall workflow, sometimes in other languages.

I’ll look into what’s possible; if you have any suggestions, I’d love to hear them.
Best,
