### ISSUE TITLE
How to extract the 3 channel intermediate output from the multiplex model

### ISSUE THREAD

**Issue by Douglas2Code** [instanseg/instanseg#68]
Hi, very nice work! 

I am wondering is there any guidance on how to extract the intermediate 3 channel output from the multiplex model?

**Comment by ThibautGoldsborough** [comment]
`
import torch
from instanseg import InstanSeg

device = "cuda"
instanseg_fluorescence = InstanSeg("fluorescence_nuclei_and_cells", device = device)

image_array, pixel_size = instanseg_fluorescence.read_image("../instanseg/examples/LuCa1.tif")

labeled_output, image_tensor  = instanseg_fluorescence.eval_medium_image(image_array, pixel_size, return_image_tensor=True, rescale_output=False)

intermediate_three_channel_output = instanseg_fluorescence.instanseg.fcn.model.AdaptorNet(image_tensor.unsqueeze(0).to(device))
`

Hi, not there's no guidance on how to do it. You use the code above to get the three channel representation. We don't support tiling this intermediate output, so hopefully your image is small enough to fit in your gpu.

**Comment by ThibautGoldsborough** [comment]
Ah that's an input size not divisible by 32 error. You can fix it with this:
`
from instanseg.utils.tiling import _instanseg_padding, _recover_padding

image_tensor, pad = _instanseg_padding(image_tensor)
intermediate_three_channel_output = instanseg_fluorescence.instanseg.fcn.model.AdaptorNet(image_tensor.to(device))
intermediate_three_channel_output = _recover_padding(intermediate_three_channel_output, pad)
`
