### ISSUE TITLE
Containerized version?

### ISSUE THREAD

**Issue by TorecLuik** [instanseg/instanseg#9]
Hey, your project looks great.

Could you supply a containerized version too?

I'd love to run it on HPC (or anywhere w/ Docker).

For example, this is the BIAFLOWS style for running CellPose 0.6 as a container: https://github.com/TorecLuik/W_NucleiSegmentation-Cellpose 
I don't particularly care about the BIAFLOWS fluff, but a container that can be run, contains pretrained models, accepting commandline parameters and describing those parameters in some json would be pretty useful. Or at least a dockerfile that encapsulates all the requirements for installing?

**Comment by alanocallaghan** [comment]
I'm not sure exactly what you'd want in this sort of container in terms of cuda versions etc, but the following dockerfile should be a decent start:


```Dockerfile
FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-runtime

RUN apt-get update -y && \
    apt-get install -y wget unzip git && \
    apt-get clean

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    chmod +x /tmp/miniconda.sh && \
    /tmp/miniconda.sh -b


RUN wget https://github.com/instanseg/instanseg/releases/download/instanseg_models_v1/brightfield_nuclei.zip && \
    unzip brightfield_nuclei.zip
RUN wget https://github.com/instanseg/instanseg/releases/download/instanseg_models_v1/fluorescence_nuclei_and_cells.zip && \
    unzip fluorescence_nuclei_and_cells.zip

RUN git clone https://github.com/instanseg/instanseg.git

RUN conda update conda

RUN conda env create -f ./instanseg/env.yml

RUN conda init && \
    . /root/.bashrc && \
    conda activate instanseg && \
    conda install pip && \
    pip install ./instanseg
```

you'd probably want to follow instructions in the InstanSeg README about adding GPU support

**Comment by TorecLuik** [comment]
Cheers! 

I'll look into setting up a build for it at some point, thanks.

**Comment by alanocallaghan** [comment]
ymmv but I was able to train and run inference on the gpu with this: https://github.com/instanseg/instanseg/pull/10/
